version: '3.7'
services:
  envoy:
    build:
      context: envoy/
    volumes:
      - type: bind
        source: ./envoy/envoy.yaml
        target: /etc/envoy.yaml
    expose:
      - '10000'
      - '10001'
    ports:
      - '10000:10000'
      - '10001:10001'

  http-app:
    build:
      context: http-app/
    expose:
      - '3000'
    ports:
      - '3000:3000'

  http-client:
    build:
      context: http-app/
    environment:
      PORT: 3001
      SRVADDR: 'http-app'
      SRVPORT: 3000
    expose:
      - '3001'
    ports:
      - '3001:3001'

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    expose:
      - '9411'
      - '16686'
    ports:
      - '9411:9411'
      - '16686:16686'
